name: "[Dispatch] Sync_ci"

on:
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: spaceone-dev
  repo: actions
  ref: master

jobs:
  pull_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ${{ env.owner }}
          repo: ${{ env.repo }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ${{ env.workflow_file_name }}
          ref: ${{ env.ref }}
          wait_interval: 10
          inputs: '{"repository" : "${{ github.repository }}" , "sync_only" : "true"}'
          trigger_workflow: true
          wait_workflow: true